#!/bin/sh

printf "===========\n"
printf "Checking current git status...\n"
printf "Did you forget to commit anything?\n"
printf "Is it in the correct branch?\n"
printf "===========\n"

git status

printf "Waiting."
sleep 1
printf "."
sleep 1
printf "."
sleep 1
printf ".\n"

printf "===========\n"
printf "Building..\n"
go build -o temp-main main.go 
if [ $? -ne 0 ]; then
  printf "\nBuild FAILED\n"
  printf "Push FAILED\n\n"
  exit 1
fi
rm temp-main
printf "Build OK\n"

printf "===========\n"
printf "Testing..\n"
go test ./... -cover -count=1
if [ $? -ne 0 ]; then
  printf "\nTest FAILED\n"
  printf "Push FAILED\n\n"
  exit 1
fi
printf "Test OK\n"

printf "===========\n"
printf "Highly recommended to run 'make lint' \n"
printf "by yourself after pushing is finished.\n"
sleep 2
#comment it out for now, taking too long
#make lint
#if [ $? -ne 0 ]; then
  #printf "\nLinting FAILED\n"
  #printf "Linting FAILED\n\n"
  #exit 1
#fi

printf "===========\n"
printf "Pushing..\n"