app:
  name: "go-user-management"
  host: "localhost"
  port: 8080
  debug: true

database:
  name: ""
  host: ""
  port: ""
  username: ""
  password: ""
  maxidleconn: 0
  maxopenconn: 0
  connmaxlifetime: 0
  scheme: ""

hasher:
  cost: 0

auth:
  accesstimeduration: 0 # in second
  accesssecretkey: ""

seed:
  admin:
    email: ""
    password: ""
