// Code generated by MockGen. DO NOT EDIT.
// Source: common.go

// Package mock_request is a generated GoMock package.
package mock_request

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGinContextDefaultQueryAdapter is a mock of GinContextDefaultQueryAdapter interface.
type MockGinContextDefaultQueryAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockGinContextDefaultQueryAdapterMockRecorder
}

// MockGinContextDefaultQueryAdapterMockRecorder is the mock recorder for MockGinContextDefaultQueryAdapter.
type MockGinContextDefaultQueryAdapterMockRecorder struct {
	mock *MockGinContextDefaultQueryAdapter
}

// NewMockGinContextDefaultQueryAdapter creates a new mock instance.
func NewMockGinContextDefaultQueryAdapter(ctrl *gomock.Controller) *MockGinContextDefaultQueryAdapter {
	mock := &MockGinContextDefaultQueryAdapter{ctrl: ctrl}
	mock.recorder = &MockGinContextDefaultQueryAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGinContextDefaultQueryAdapter) EXPECT() *MockGinContextDefaultQueryAdapterMockRecorder {
	return m.recorder
}

// DefaultQuery mocks base method.
func (m *MockGinContextDefaultQueryAdapter) DefaultQuery(key, defaultValue string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultQuery", key, defaultValue)
	ret0, _ := ret[0].(string)
	return ret0
}

// DefaultQuery indicates an expected call of DefaultQuery.
func (mr *MockGinContextDefaultQueryAdapterMockRecorder) DefaultQuery(key, defaultValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultQuery", reflect.TypeOf((*MockGinContextDefaultQueryAdapter)(nil).DefaultQuery), key, defaultValue)
}
