// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/google/wire"
	"github.com/resyahrial/go-user-management/internal/entities"
	"github.com/resyahrial/go-user-management/internal/repositories/pg/repo/user"
	"github.com/resyahrial/go-user-management/internal/usecase/user"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitUserUsecase(db *gorm.DB) entities.UserUsecase {
	userRepoImpl := repo.NewUserRepo(db)
	userUsecase := usecase.NewUserUsecase(userRepoImpl)
	return userUsecase
}

// injector.go:

var userRepoAdapterSet = wire.NewSet(repo.NewUserRepo, wire.Bind(new(usecase.UserRepo), new(*repo.UserRepoImpl)))
