#!/bin/bash

while getopts "e:" arg; do
  case $arg in
    e) Env=$OPTARG;;
  esac
done


# Start the HTTP service locally
# if config on yaml file
# go run ./cmd/app-http/*.go -env=$Env 

# if config on env file
source files/etc/env/env.$Env.sh
go run ./cmd/app-http/*.go